[package]
name = "sse-codec"
version = "0.1.0"
authors = ["Renée Kooi <renee@kooi.me>"]
edition = "2018"

[dependencies]
futures_codec = "0.3.1"
futures-io = "0.3"
bytes = "0.4"
memchr = "2.2"

[dev-dependencies]
surf = { git = "https://github.com/http-rs/surf", branch = "futures-0.3", default-features = false, features = ["native-client"] }
async-std = "1.0"
futures = "0.3"
